# Generated by Django 2.0.3 on 2018-04-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('year', models.CharField(max_length=200, verbose_name='Слоган')),
                ('runtime', models.IntegerField(verbose_name='Время')),
            ],
        ),
    ]
