# Generated by Django 2.0.3 on 2018-04-01 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmsApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='year',
            new_name='slogan',
        ),
    ]
