# Generated by Django 2.0.3 on 2018-04-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmsApi', '0002_auto_20180401_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.CharField(max_length=100, null=True, verbose_name='Актеры'),
        ),
        migrations.AddField(
            model_name='film',
            name='boxOffice',
            field=models.CharField(max_length=20, null=True, verbose_name='Прокат'),
        ),
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.CharField(max_length=25, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.CharField(max_length=50, null=True, verbose_name='Режисер'),
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.CharField(max_length=50, null=True, verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='film',
            name='language',
            field=models.CharField(max_length=30, null=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='film',
            name='plot',
            field=models.CharField(max_length=250, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.CharField(max_length=100, null=True, verbose_name='URL-постер'),
        ),
        migrations.AddField(
            model_name='film',
            name='production',
            field=models.CharField(max_length=30, null=True, verbose_name='Продакшн компания'),
        ),
        migrations.AddField(
            model_name='film',
            name='rated',
            field=models.CharField(max_length=15, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='film',
            name='released',
            field=models.CharField(max_length=25, null=True, verbose_name='Дата релиза'),
        ),
        migrations.AddField(
            model_name='film',
            name='writer',
            field=models.CharField(max_length=50, null=True, verbose_name='Сценарист'),
        ),
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.IntegerField(null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='film',
            name='runtime',
            field=models.IntegerField(null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='film',
            name='slogan',
            field=models.CharField(max_length=200, null=True, verbose_name='Слоган'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
    ]
