# Generated by Django 2.0.3 on 2018-04-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmsApi', '0003_auto_20180401_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Omdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omdbId', models.CharField(max_length=50, verbose_name='omdbId')),
                ('flag', models.BooleanField(verbose_name='flag')),
            ],
        ),
    ]
